version: '1.0'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: fjudge:latest 
    ports:
      - "8008:80"
    environment:
      - TZ=Asia/Jakarta
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
